# The optaplanner configuration has been moved to OptaPlannerConfiguration.java
# to resolve a persistent binding issue.

# Logging Configuration
logging:
  level:
    com.school.timetabling: DEBUG
    org.optaplanner: INFO
    org.springframework: WARN
    org.hibernate: WARN

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 300000 # 5 minutes